name: Deploiement EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Déploiement sur EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            rm -rf SaoneLocal
            git clone https://github.com/angelinacarvelli/SaoneLocal.git
            cd SaoneLocal

            cp ~/saonelocal.env .env

            sudo docker compose down || true
            sudo docker compose up -d --build
            sudo docker compose exec -T saonelocal npm run seed || true
            sudo docker compose ps