name: Deploiement EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # 1. On vérifie d'abord que le projet compile bien
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Vérifier le build Docker
        run: |
          docker build -t test-build .

  # 2. Si le build est OK, on déploie sur ton EC2
  deploy:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Connexion au serveur EC2 et Déploiement
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Installer Git si manquant
            if ! command -v git &> /dev/null; then
              sudo dnf install git -y || sudo apt-get install git -y
            fi

            # Nettoyer et cloner le dépôt
            rm -rf SaoneLocal
            git clone https://github.com/angelinacarvelli/SaoneLocal.git
            cd SaoneLocal

            # 1. Supprimer TOUS les anciens conteneurs pour libérer le port 80
            sudo docker stop saonelocal || true
            sudo docker rm saonelocal || true
            sudo docker stop mon-app || true
            sudo docker rm mon-app || true

            # 2. Build de la nouvelle image
            sudo docker build -t mon-app .

            # 3. Lancement sur le bon port (80 accessible depuis l'extérieur)
            sudo docker run -d --name mon-app -p 80:80 --restart always mon-app
          
            echo "VÉRIFICATION DES PORTS UTILISÉS SUR L'EC2"
            sudo ss -tulnp | grep :80 || true
            
            echo "QUELS CONTENEURS TOURNE ?"
            sudo docker ps -a
            
            echo "LOG DE MON-APP "
            sudo docker logs mon-app || true